# Generated by Django 5.0.1 on 2024-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_customeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='User',
        ),
    ]
