# Generated by Django 5.0.1 on 2024-05-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='que',
            new_name='quantity',
        ),
    ]
